xpos314/xpos314.web/Controllers/AuthController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using xpos314.datamodels;
using xpos314.viewmodels;
using xpos314.web.Services;

namespace xpos314.web.Controllers
{
    public class AuthController : Controller
    {
        private AuthService authService;
        VMResponse respon = new VMResponse();

        public AuthController(AuthService _authService)
		{
			this.authService = _authService;
		}

		public IActionResult Login()
        {
            return PartialView();
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public async Task<JsonResult> LoginSubmit(string email, string password)
        {
            VMCustomer customer = await authService.CheckLogin(email, password);

            if (customer != null)
            {
                respon.Message = $"Hallo, {customer.NameCustomer} welcome to XPOS";
                HttpContext.Session.SetString("NameCustomer", customer.NameCustomer);
                HttpContext.Session.SetInt32("IdCustomer", customer.Id);
                HttpContext.Session.SetInt32("IdRole", customer.IdRole ?? 0);
            }
            else
            {
                respon.Message = $"Oops, {email} notfound or password is wrong, please check it!";
            }
            return Json(new {dataRespon = respon});
        }

        public IActionResult Register()
        {
            return PartialView();
        }

        [HttpPost]
        public async Task<JsonResult> Register(TblCustomer customer)
        {
            respon = await authService.CreateCustomer(customer);
            return Json(new { dataRespon = respon });
        }
        public async Task<JsonResult> CheckEmailExisting(string email)
        {
            bool isExist = await authService.CheckEmailExisting(email);
            return Json(isExist);
        }
    }
}

xpos314/xpos314.web/Controllers/FriendController.cs
using Microsoft.AspNetCore.Mvc;
using xpos314.web.Models;

namespace xpos314.web.Controllers
{
    public class FriendController : Controller
    {
        // list adalah in memori
            private static List<Friend> list = new List<Friend>()
            {
                new Friend {Id = 1, Name = "Muafa", Address= "Bogor"},
                new Friend {Id = 2, Name = "Marchelino", Address= "Jakarta"},
                new Friend {Id = 3, Name = "Laudry", Address= "Depok"},
            };
        public IActionResult Index()
        {
            ViewBag.listFriend = list;

            return View(list);
        }

        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Create(Friend friend)
        {
            list.Add(friend);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            Friend friend = list.Find(a => a.Id == id)!;
            return View(friend);
        }

        [HttpPost]
        public IActionResult Edit(Friend data)
        {
            Friend friend = list.Find(a => a.Id == data.Id)!;
            int index = list.IndexOf(friend);
            if (index > -1)
            {
                list[index].Id = data.Id;
                list[index].Name = data.Name;
                list[index].Address = data.Address;
            }
            return RedirectToAction("Index");
        }

        public IActionResult Detail(int id)
        {
            Friend friend = list.Find(a => a.Id == id)!;
            return View(friend);
        }

        //public IActionResult Delete(int id)
        //{
        //    Friend friend = list.Find(a => a.Id == id)!;
        //    return View(friend);
        //}

        //[HttpPost]
        //public IActionResult Delete(String id)
        //{
        //    Friend data = list.Find(a => a.Id == int.Parse(id))!;
        //    list.Remove(data);
        //    return RedirectToAction("Index");
        //}

        [HttpGet]
        [HttpPost]
        public IActionResult Delete(int id)
        {
            Friend friend = list.Find(a => a.Id == id)!;
            if (HttpContext.Request.Method == "post")
            {
                list.Remove(friend);
                return RedirectToAction("Index");
            }
            else
            {
                return View(friend);
            }
        }
    }
}

xpos314/xpos314.web/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using xpos314.viewmodels;
using xpos314.web.Services;

namespace xpos314.web.Controllers
{
    public class OrderController : Controller
    {
        private ProductService productService;
        private OrderService orderService;
        private int IdUser = 1;

        public OrderController(ProductService _productService, OrderService _orderService)
        {
            this.productService = _productService;
            this.orderService = _orderService;
        }

        public async Task<IActionResult> Catalog(VMSearchPage dataSearch)
        {
            List<VMTblProduct> dataProduct = await productService.GetAllData();
            dataSearch.MinAmount = dataSearch.MinAmount == null ? decimal.MinValue : dataSearch.MinAmount;
            dataSearch.MaxAmount = dataSearch.MaxAmount == null ? decimal.MaxValue : dataSearch.MaxAmount;

            if (dataSearch.NameProduct != null)
                dataProduct = dataProduct.Where(a => a.NameProduct == dataSearch.NameProduct).ToList();

            if (dataSearch.MinAmount != null && dataSearch.MaxAmount != null)
                dataProduct = dataProduct.Where(a => a.Price >= dataSearch.MinAmount && a.Price < dataSearch.MaxAmount).ToList();

            //Set Session in VMOrderHeader first load
            VMOrderHeader dataHeader = HttpContext.Session.GetComplexData<VMOrderHeader>("ListCart");
            if (dataHeader == null)
            {
                dataHeader = new VMOrderHeader();
                dataHeader.ListDetails = new List<VMOrderDetail>();
            }
            var ListDetail = JsonConvert.SerializeObject(dataHeader.ListDetails);
            ViewBag.dataHeader = dataHeader;
            ViewBag.dataDetail = ListDetail;
            //End set session

            ViewBag.Search = dataSearch;
            ViewBag.CurrentPageSize = dataSearch.CurrentPageSize;


            return View(PaginationList<VMTblProduct>.CreateAsync(dataProduct, dataSearch.pageNumber ?? 1, dataSearch.pageSize ?? 3));
        }

        [HttpPost]
        public JsonResult SetSession(VMOrderHeader dataHeader)
        {
            HttpContext.Session.SetComplexdata("ListCart", dataHeader);
            return Json("");
        }

        public IActionResult OrderPreview(VMOrderHeader dataHeader)
        {
            return PartialView(dataHeader);
        }
        public IActionResult SearchMenu()
        {
            return PartialView();
        }

        [HttpPost]
        public async Task<JsonResult> SubmitOrder(VMOrderHeader dataHeader)
        {
            //int IdCustomer = HttpContext.Session.GetInt32("IdCustomer") ?? 0;
            //dataHeader.IdCustomer = IdCustomer;
            dataHeader.IdCustomer = IdUser;

            VMResponse respon = await orderService.SubmitOrder(dataHeader);

            return Json(respon);
        }

        public async Task<IActionResult> HistoryOrder(VMSearchPage dataSearch)
        {
            //int IdCustomer = HttpContext.Session.GetInt32("IdCustomer" ?? 0);
            int IdCustomer = IdUser;
            List<VMOrderHeader> data = await orderService.ListHeaderDetails(IdCustomer);
            int count = await orderService.CountTransaction(IdCustomer);
            ViewBag.Count = count;

            dataSearch.MinDate = dataSearch.MinDate == null ? DateTime.MinValue : dataSearch.MinDate;
            dataSearch.MaxDate= dataSearch.MaxDate == null ? DateTime.MaxValue : dataSearch.MaxDate;

            dataSearch.MinAmount = dataSearch.MinAmount == null ? decimal.MinValue : dataSearch.MinAmount;
            dataSearch.MaxAmount = dataSearch.MaxAmount == null ? decimal.MaxValue : dataSearch.MaxAmount;

            if (!string.IsNullOrEmpty( dataSearch.CodeTransaction))
            {
                data = data.Where(a => a.CodeTransaction.ToLower().Contains(dataSearch.CodeTransaction.ToLower())).ToList();
            }

            if (dataSearch.MinDate != null && dataSearch.MaxDate != null)
            {
                data = data.Where(a => a.CreateDate >= dataSearch.MinDate && a.CreateDate <= dataSearch.MaxDate).ToList();
            }

            if (dataSearch.MinAmount!= null && dataSearch.MaxAmount != null)
            {
                data = data.Where(a => a.Amount >= dataSearch.MinAmount && a.Amount <= dataSearch.MaxAmount).ToList();
            }
            ViewBag.Search = dataSearch;
            return View(data);
        }
        public IActionResult Search()
        {
            return PartialView();
        }

        //remove session
        public JsonResult RemoveSession()
        {
            HttpContext.Session.Remove("ListCart");
            return Json("");
        }
    }
}

xpos314/xpos314.web/Controllers/RoleController.cs
using Microsoft.AspNetCore.Mvc;
using xpos314.datamodels;
using xpos314.viewmodels;
using xpos314.web.Services;

namespace xpos314.web.Controllers
{
    public class RoleController : Controller
    {
        private readonly XPOS_314Context db;
        private readonly RoleService roleService;

        public RoleController(RoleService _roleService)
        {
            this.roleService = _roleService;
        }
        public async Task<IActionResult> Index(string sortOrder,
                                               string searchString,
                                               string currentFilter,
                                               int? pageNumber,
                                               int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            List<VMRole> data = await roleService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.RoleName.ToLower().Contains(searchString.ToLower())
                    ).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.RoleName).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.RoleName).ToList();
                    break;
            }

            return View(PaginationList<VMRole>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
        }
        public async Task<JsonResult> CheckNameIsExist(string roleName)
        {
            bool isExist = await roleService.CheckCategoryByName(roleName);
            return Json(isExist);
        }
        public async Task<IActionResult> Create()
        {
            VMRole data = new VMRole();

            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> Create([FromForm] VMRole dataParam)
        {

            VMResponse respon = await roleService.Create(dataParam);
            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }

        public async Task<IActionResult> Edit(int id)
        {
            VMRole data = await roleService.GetDataById(id);

            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([FromForm] VMRole dataParam)
        {

            VMResponse respon = await roleService.Edit(dataParam);
            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }

        public async Task<IActionResult> Delete(int id)
        {
            VMRole data = await roleService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> SureDelete(int id)
        {
            VMResponse respon = await roleService.Delete(id);
            if (respon.Success)
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index", id);
        }

        public async Task<IActionResult> Detail(int id)
        {
            VMRole data = await roleService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> RestoreData(int id)
        {
            VMResponse respon = await roleService.Delete(id);
            if (respon.Success)
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index", id);
        }
    }
}

xpos314/xpos314.web/Views/Shared/_LayoutOld.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - xpos314.web</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/xpos314.web.styles.css" asp-append-version="true" />
	 <!-- JQUERY -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
     <!-- Icons -->
    <script src="https://unpkg.com/feather-icons"></script>

</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">xpos314.web</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Friend" asp-action="Index">Friend</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="CategoryTry" asp-action="Index">Category Try</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2023 - xpos314.web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<!-- Modal -->
	<!-- Modal -->
	<div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
		<div class="modal-dialog modal-lg">
			<div class="modal-content">
				<div class="modal-header">
					<h1 class="modal-title fs-5" id="exampleModalLabel"></h1>
					<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
				</div>
				<div class="modal-body" id="body_modal">
				</div>
			</div>
		</div>
	</div>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
	<script>feather.replace();</script>
	@await RenderSectionAsync("Scripts", required: false)

</body>
</html>

xpos314/xpos314.web/Views/Shared/_Sidebar.cshtml
@using xpos314.web.Services
@inject AuthService authService
@{
	int IdCustomer = @Context.Session.GetInt32("IdCustomer") ?? 0;
	int IdRole = @Context.Session.GetInt32("IdRole") ?? 0;
	string NameCustomer = @Context.Session.GetString("NameCustomer") ?? "";
	var menus = await authService.MenuAccess(IdRole);
}

<!-- ============================================================== -->
<!-- Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->
<aside class="left-sidebar" data-sidebarbg="skin6">
	<div class="scroll-sidebar" data-sidebarbg="skin6">
		<!-- Sidebar Menu -->
		<nav class="sidebar-nav">
			<ul id="sidebarnav">
				@*<li class="sidebar-item">
				<a class="sidebar-link sidebar-link" href="~/Home/Index"
				aria-expanded="false">
				<i data-feather="home" class="feather-icon"></i><span class="hide-menu">Dashboard</span>
				</a>
				</li>*@
				<li class="list-divider"></li>
				@foreach (var parent in menus)
				{

					<li class="sidebar-item">
						<a asp-controller="@parent.MenuController" asp-action="@parent.MenuAction" class="sidebar-link">
							<i class="feather-icon" data-feather="@parent.MenuIcon"></i>
							<span class="hide-menu">
								@parent.MenuName
							</span>
						</a>
					</li>

				}
				@if (IdCustomer != 0)
				{
					<li class="list-divider"></li>
					<li class="sidebar-item">
						<a class="sidebar-link sidebar-link" asp-controller="Auth" asp-action="Logout"
					   aria-expanded="false">
							<i data-feather="log-out" class="feather-icon"></i><span class="hide-menu">Logout</span>
						</a>
					</li>
				}
				@*<div class="scroll-sidebar" data-sidebarbg="skin6">
				<nav class="sidebar-nav">
				<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">*@
				<!-- Add icons to the links using the .nav-icon class
					 with font-awesome or any other icon font library -->
				@*	@foreach (var parent in menus)
				{
				<li class="sidebar-item">
				<a asp-controller="@parent.MenuController" asp-action="@parent.MenuAction" class="sidebar-link">
				<i class="@parent.MenuIcon feather-icon"></i>
				<p>@parent.MenuName</p>
				</a>
				</li>
				}
				@if (IdCustomer != 0)
				{
				<li class="list-divider"></li>
				<li class="sidebar-item">
				<a class="sidebar-link sidebar-link" asp-controller="Auth" asp-action="Logout"
				aria-expanded="false">
				<i data-feather="log-out" class="feather-icon"></i><span class="hide-menu">Logout</span>
				</a>
				</li>
				}*@

				@*@foreach (var parent in menus)
				{
				<li class="nav-item menu-open">
				<a href="#" class="nav-link">
				<i class="nav-icon @parent.MenuIcon"></i>
				<p>
				@parent.MenuName
				<i class="right fas fa-angle-left"></i>
				</p>
				</a>
				<ul class="nav nav-treeview">

				@foreach (var child in parent.ListChild)
				{
				<li class="nav-item">
				<a asp-controller="@child.MenuController" asp-action="@child.MenuAction" class="nav-link">
				<i class="@child.MenuIcon nav-icon"></i>
				<p>@child.MenuName</p>
				</a>
				</li>
				}
				</ul>
				</li>
				}*@

			</ul>
		</nav>
		<!-- /.sidebar-menu -->
		<!-- Sidebar scroll-->
		@*<div class="scroll-sidebar" data-sidebarbg="skin6">
		<!-- Sidebar navigation-->
		@if (IdCustomer != 0)
		{

		<nav class="sidebar-nav">
		<ul id="sidebarnav">
		<li class="sidebar-item">
		<a class="sidebar-link sidebar-link" href="~/Home/Index"
		aria-expanded="false">
		<i data-feather="home" class="feather-icon"></i><span class="hide-menu">Dashboard</span>
		</a>
		</li>
		<li class="list-divider"></li>
		<li class="nav-small-cap"><span class="hide-menu">Master</span></li>

		<li class="sidebar-item">
		<a class="sidebar-link" asp-action="Index" asp-controller="Friend"
		aria-expanded="false">
		<i data-feather="tag" class="feather-icon"></i><span class="hide-menu">
		Friends
		</span>
		</a>
		</li>
		<li class="sidebar-item">
		<a class="sidebar-link sidebar-link" asp-action="Index" asp-controller="CategoryTry"
		aria-expanded="false">
		<i data-feather="message-square" class="feather-icon"></i><span class="hide-menu">Category Try</span>
		</a>
		</li>
		<li class="sidebar-item">
		<a class="sidebar-link sidebar-link" asp-action="Index" asp-controller="VariantTry"
		aria-expanded="false">
		<i data-feather="message-square" class="feather-icon"></i><span class="hide-menu">Variant Try</span>
		</a>
		</li>
		<li class="sidebar-item">
		<a class="sidebar-link sidebar-link" asp-action="Index" asp-controller="Category"
		aria-expanded="false">
		<i data-feather="message-square" class="feather-icon"></i><span class="hide-menu">Kategori</span>
		</a>
		</li>
		<li class="sidebar-item">
		<a class="sidebar-link sidebar-link" asp-action="Index" asp-controller="Variant"
		aria-expanded="false">
		<i data-feather="message-square" class="feather-icon"></i><span class="hide-menu">Variant</span>
		</a>
		</li>
		<li class="sidebar-item">
		<a class="sidebar-link sidebar-link" asp-action="Index" asp-controller="Product"
		aria-expanded="false">
		<i data-feather="message-square" class="feather-icon"></i><span class="hide-menu">Product</span>
		</a>
		</li>

		<li class="list-divider"></li>
		<li class="nav-small-cap"><span class="hide-menu">Menu Kalbe</span></li>
		<li class="sidebar-item">
		<a class="sidebar-link sidebar-link" asp-action="Index" asp-controller="Produk"
		aria-expanded="false">
		<i data-feather="message-square" class="feather-icon"></i><span class="hide-menu">Product Kalbe</span>
		</a>
		</li>
		<li class="sidebar-item">
		<a class="sidebar-link sidebar-link" asp-action="Index" asp-controller="CustomerKalbe"
		aria-expanded="false">
		<i data-feather="message-square" class="feather-icon"></i><span class="hide-menu">Costumer Kalbe</span>
		</a>
		</li>
		<li class="sidebar-item">
		<a class="sidebar-link sidebar-link" asp-action="Index" asp-controller="PenjualanKalbe"
		aria-expanded="false">
		<i data-feather="message-square" class="feather-icon"></i><span class="hide-menu">Penjualan Kalbe</span>
		</a>
		</li>

		<li class="list-divider"></li>
		<li class="nav-small-cap"><span class="hide-menu">User Configuration</span></li>
		<li class="sidebar-item">
		<a class="sidebar-link sidebar-link" asp-action="Index" asp-controller="Role"
		aria-expanded="false">
		<i data-feather="message-square" class="feather-icon"></i><span class="hide-menu">Role</span>
		</a>
		</li>
		<li class="sidebar-item">
		<a class="sidebar-link sidebar-link" asp-action="Index" asp-controller="Customer"
		aria-expanded="false">
		<i data-feather="message-square" class="feather-icon"></i><span class="hide-menu">Costumer</span>
		</a>
		</li>

		<li class="list-divider"></li>
		<li class="nav-small-cap"><span class="hide-menu">Transaction</span></li>

		<li class="sidebar-item">
		<a class="sidebar-link" asp-controller="Order" asp-action="Catalog"
		aria-expanded="false">
		<i data-feather="book-open" class="feather-icon"></i>
		<span class="hide-menu">Menu Catalog</span>
		</a>
		</li>
		<li class="sidebar-item">
		<a class="sidebar-link sidebar-link" asp-controller="Order" asp-action="HistoryOrder"
		aria-expanded="false">
		<i data-feather="clipboard" class="feather-icon"></i>
		<span class="hide-menu">History Order</span>
		</a>
		</li>

		<li class="list-divider"></li>
		<li class="sidebar-item">
		<a class="sidebar-link sidebar-link" asp-controller="Auth" asp-action="Logout"
		aria-expanded="false">
		<i data-feather="log-out" class="feather-icon"></i><span class="hide-menu">Logout</span>
		</a>
		</li>
		</ul>
		</nav>
		}*@
		<!-- End Sidebar navigation -->
	</div>
	<!-- End Sidebar scroll-->
</aside>
<!-- ============================================================== -->
<!-- End Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->