xpos314/xpos314.web/Controllers/CategoryTryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using xpos314.datamodels;
using xpos314.viewmodels;
using xpos314.web.Services;

namespace xpos314.web.Controllers
{
    public class CategoryTryController : Controller
    {
        private readonly XPOS_314Context db;
        private readonly CategoryTryService categoryTryService;

        public CategoryTryController(XPOS_314Context _db)
        {
            this.db = _db;
            this.categoryTryService = new CategoryTryService(db);
        }

        public IActionResult Index()
        {
            List<VMTblCategory> dataView = categoryTryService.GetAllData();
            return View(dataView);
        }

        public IActionResult Create()
        {
            VMTblCategory viewModel = new VMTblCategory();
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Create(VMTblCategory dataView)
        {
            VMResponse respon = new VMResponse();

            if (ModelState.IsValid)
            {
                respon = categoryTryService.Create(dataView);

                if (respon.Success)
                {
                    return RedirectToAction("Index");
                }
            }

            respon.Entity = dataView;
            return View(respon.Entity);
        }

        public IActionResult Edit(int id)
        {
            VMTblCategory dataView = categoryTryService.GetById(id);
            return View(dataView);
        }

        [HttpPost]
        public IActionResult Edit(VMTblCategory dataView)
        {
            VMResponse respon = new VMResponse();

            if (ModelState.IsValid)
            {
                respon = categoryTryService.Edit(dataView);
                if (respon.Success)
                {
                    return RedirectToAction("Index");
                }
            }

            respon.Entity = dataView;
            return View(respon.Entity);
        }

        public IActionResult Detail(int id)
        {
            VMTblCategory dataView = categoryTryService.GetById(id);
            return View(dataView);
        }


        public IActionResult Delete(int id)
        {
            VMTblCategory dataView = categoryTryService.GetById(id);
            return View(dataView);
        }

        [HttpPost]
        public IActionResult Delete(VMTblCategory dataView)
        {
            VMResponse respon = new VMResponse();

            ModelState.Remove("NameCategory");
            if (ModelState.IsValid)
            {
                respon = categoryTryService.Delete(dataView);
                if (respon.Success)
                {
                    return RedirectToAction("Index");
                }
            }

            respon.Entity = dataView;
            return View(respon.Entity);
        }
    }
}

xpos314/xpos314.web/Views/CategoryTry/Create.cshtml
﻿@using xpos314.viewmodels
@model VMTblCategory
@{
	Layout = null;
	ViewData["Title"] = "Create Category";
}
<div class="card mt-4">
	<div class="card-body">
		<h4>@ViewData["Title"]</h4>
		<form asp-action="Create" method="POST">
			<div class="form-group row mb-2">
				<label for="NameCategory" class="col-sm-2 col-form-label">Name Category</label>
				<div class="col-sm-10">
					<input type="text" class="form-control" name="NameCategory" id="NameCategory" value="@Model.NameCategory">
					<span class="text-danger" asp-validation-for="NameCategory"></span>
				</div>
			</div>
			<div class="form-group row mb-2">
				<label for="Description" class="col-sm-2 col-form-label">Description</label>
				<div class="col-sm-10">
					<input type="text" class="form-control" name="Description" id="Description">
				</div>
			</div>
			<div class="form-group row">
				<div class="col-sm-10">
					<button type="submit" class="btn btn-primary">Submit</button>
					<a class="btn btn-secondary" asp-controller="CategoryTry" asp-action="Index">Back</a>
				</div>
			</div>
		</form>
	</div>
</div>

xpos314/xpos314.web/Views/CategoryTry/Delete.cshtml
﻿@using xpos314.viewmodels
@model VMTblCategory
@{
    Layout=null;
      ViewData["Title"] = "Delete Category";
}

<div class="card">
    <div class="card-body">
        <form asp-action="Delete" method="POST">
            <input type="hidden" id="Id" name="Id" value="@Model.Id"/>

            <h3>Are you sure for delete @Model.NameCategory ?</h3>

            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Yes</button>
                <a asp-action="Index" class="btn btn-secondary">Back to List</a>
            </div>
        </form>
    </div>
</div>

xpos314/xpos314.web/Views/CategoryTry/Detail.cshtml
﻿@using xpos314.viewmodels
@model VMTblCategory
@{
      Layout=null;
      ViewData["Title"] = "Detail Category";
}
<div class="card">
    <div class="card-header d-lg-flex">
        <h3 class="card-title font-weight-bold mr-2 mt-2">@ViewData["Title"]</h3>  
    </div>
    <div class="card-body">
  <div class="form-group row mb-2">
    <label for="NameCategory" class="col-sm-2 col-form-label">Name Category</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" name="NameCategory" id="NameCategory" value="@Model.NameCategory" readonly>
      <span class="text-danger" asp-validation-for="NameCategory"></span>
    </div>
  </div>
  <div class="form-group row mb-2">
    <label for="Description" class="col-sm-2 col-form-label">Description</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" name="Description" id="Description" value="@Model.Description" readonly>
    </div>
  </div>
</div>
</div>

xpos314/xpos314.web/Views/CategoryTry/Edit.cshtml
﻿@using xpos314.viewmodels
@model VMTblCategory
@{
	Layout = null;
	ViewData["Title"] = "Edit Category";
}
<div class="card">
	<div class="card-body">
		<h4 mb-2>@ViewData["Title"]</h4>
		<form asp-action="Edit" method="POST">
			<input type="hidden" id="Id" name="Id" value="@Model.Id" />
			<div class="form-group row mb-2">
				<label for="NameCategory" class="col-sm-2 col-form-label">Name Category</label>
				<div class="col-sm-10">
					<input type="text" class="form-control" name="NameCategory" id="NameCategory" value="@Model.NameCategory" required/>
					@*<span class="text-danger" asp-validation-for="NameCategory"></span>*@
				</div>
			</div>
			<div class="form-group row mb-2">
				<label for="Description" class="col-sm-2 col-form-label">Description</label>
				<div class="col-sm-10">
					<input type="text" class="form-control" name="Description" id="Description" value="@Model.Description">
				</div>
			</div>
			&nbsp;
			<div class="form-group row">
				<div class="col-sm-10">
					<button type="submit" class="btn btn-primary">Submit</button>
					<a class="btn btn-secondary" asp-controller="CategoryTry" asp-action="Index">Back</a>
				</div>
			</div>
		</form>
	</div>
</div>

xpos314/xpos314.web/Views/CategoryTry/Index.cshtml
﻿@using xpos314.viewmodels
@{
	ViewData["Title"] = "Category Try";
}

<div class="card">
	<div class="card-body">

		<h1>@ViewData["Title"]</h1>

		<div class="row">
			<form asp-action="Index" method="get" id="form_search">

				<div class="col-12">
					<div class="customize-input float-right">
						<div class="input-group">
							<div class="input-group-prepend ">
								@*<div class="row">
								<div class="col-sm">
								<input type="text" class="form-control" name="searchString" value="@ViewBag.currentFilter" placeholder="Search.." />
								</div>
								<div class="col-sm">
								<div class="input-group-text" id="btn_search">
								<i class="bi bi-search"></i>
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
								<path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
								</svg>
								</div>
								</div>

								</div>*@
								@*<button type="button" class="btn btn-secondary" id="btn_search">Search</button>*@
								<div class="input-group">
									<input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
										   aria-label="Search" aria-describedby="basic-addon2">
									<div class="input-group-append">
										<button class="btn btn-primary" type="button">
											<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"  color="white" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
												<path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
											</svg>
										</button>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</form>
		</div>

		<button class="btn btn-primary btn-sm mt-2 mb-2 btn-rounded" id="btn_add" style="float: right">Create</button>
		<table class="table table-hover">
			<thead>
				<tr>
					<th scope="col">#</th>
					<th scope="col">Name Category</th>
					<th scope="col">Description</th>
					<th scope="col">Action</th>
				</tr>
			</thead>
			<tbody>
				@foreach (VMTblCategory item in Model)
				{
					<tr>
						<th scope="row">@item.Id</th>
						<td>@item.NameCategory</td>
						<td>@item.Description</td>
						<td>
							<a class="btn btn-warning btn-sm btn_edit" data-id="@item.Id"><i data-feather="edit"></i>Edit</a> &nbsp;
							<a class="btn btn-success btn-sm btn_detail" data-id="@item.Id"> <i data-feather="user-check"></i>Detail</a> &nbsp;
							<a class="btn btn-danger btn-sm btn_delete" data-id="@item.Id"> <i data-feather="trash"></i>Delete</a>
						</td>
					</tr>
				}
			</tbody>
		</table>
	</div>
</div>

<script>
	$(document).ready(function() {
		$("#btn_add").click(function() {
			$("#body_modal").load("/CategoryTry/Create");
			$("#myModal").modal("show");
			//alert("masuk");
		});

		$(".btn_edit").click(function() {
			var id = $(this).data("id")
			$("#body_modal").empty()
			$("#body_modal").load("/CategoryTry/Edit?id=" + id);
			$("#myModal").modal("show");
		});

		$(".btn_detail").click(function() {
			var id = $(this).data("id")
			$("#body_modal").empty()
			$("#body_modal").load("/CategoryTry/Detail?id=" + id);
			$("#myModal").modal("show");
		});

		$(".btn_delete").click(function() {
			var id = $(this).data("id")
			$("#body_modal").empty()
			$("#body_modal").load("/CategoryTry/Delete?id=" + id);
			$("#myModal").modal("show");
		});
		$("#btn_search").click(function() {
			//alert("oke")
			$("#form_search").submit()
		})
	});
</script>