xpos314/xpos314.web/Controllers/VariantController.cs
using Microsoft.AspNetCore.Mvc;
using xpos314.datamodels;
using xpos314.viewmodels;
using xpos314.web.Services;

namespace xpos314.web.Controllers
{
	public class VariantController : Controller
	{
        private CategoryService categoryService;
        private VariantService variantService;
		private int IdUser = 1;

        public VariantController(CategoryService _categoryService, VariantService _variantService)
        {
            this.categoryService = _categoryService;
            this.variantService = _variantService;
        }
        public async Task<IActionResult> Index(string sortOrder,
                                               string searchString,
                                               string currentFilter,
                                               int? pageNumber,
                                               int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            List<VMTblVariant> data = await variantService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.NameVariant.ToLower().Contains(searchString.ToLower()) || a.NameCategory.ToLower().Contains(searchString.ToLower()) || a.Description.ToLower().Contains(searchString.ToLower())
                    ).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.NameVariant).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.NameVariant).ToList();
                    break;
            }

            return View(PaginationList<VMTblVariant>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
        }

        public async Task<IActionResult> Create()
		{
            VMTblVariant data = new VMTblVariant();

            List<TblCategory> listCategory = await categoryService.GetAllData();
            ViewBag.ListCategory = listCategory;

            return PartialView(data);
		}

		[HttpPost]
        public async Task<IActionResult> Create(VMTblVariant dataParam)
		{
            VMResponse respon = await variantService.Create(dataParam);
            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }

        //UNTUK PARAMETER INT ID ITU KITA SAMAKAN DI INDEX UNTUK JQUERY MENAMPILKAN MODAL SESUAI ID
        public async Task<IActionResult> Edit(int id)
        {
            VMTblVariant data = await variantService.GetDataById(id);
            List<TblCategory> listCategory = await categoryService.GetAllData();
            ViewBag.ListCategory = listCategory;
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(VMTblVariant dataParam)
        {
            VMResponse respon = await variantService.Edit(dataParam);
            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }

        public async Task<IActionResult> Delete(int id)
        {
            VMTblVariant data = await variantService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> SureDelete(int id)
        {
            VMResponse respon = await variantService.Delete(id);
            if (respon.Success)
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index", id);
        }

        public async Task<IActionResult> Detail(int id)
        {
            VMTblVariant data = await variantService.GetDataById(id);
            return PartialView(data);
        }
    }
}

xpos314/xpos314.web/Views/Variant/Create.cshtml
@using xpos314.viewmodels
@model VMTblVariant
@{
	ViewData["Title"] = "Create Variant";
}
<div class="card mt-4">
	<div class="card-body">
		<h4>@ViewData["Title"]</h4>
		<form asp-action="Create" method="post" id="form_input">
			<div class="form-group row mb-2">
				<label for="NameVariant" class="col-sm-4 col-form-label">Name Variant</label>
				<div class="col-sm-8">
					<input type="text" class="form-control" name="NameVariant" id="NameVariant" required value="@Model.NameVariant">
				</div>
			</div>
			<div class="form-group row mb-2">
				<label for="IdCategory" class="col-sm-4 col-form-label">Name Category</label>
				<div class="col-sm-8">
					@Html.DropDownList("IdCategory",
					new SelectList(ViewBag.ListCategory, "Id", "NameCategory"),
					"--Pilih Kategori--",
					new { @class = "form-control" }
					)
				</div>
			</div>
			<div class="form-group row mb-2">
				<label for="Description" class="col-sm-4 col-form-label">Description</label>
				<div class="col-sm-8">
					<input type="text" class="form-control" name="Description" id="Description">
				</div>
			</div>
			<div class="form-group row">
				<div class="col-sm-10">
					<button type="submit" class="btn btn-primary">Submit</button>
					<a class="btn btn-secondary" asp-controller="Variant" asp-action="Index">Back</a>
				</div>
			</div>
		</form>
	</div>
</div>

<script>
	$("#form_input").validate({
		errorClass: "is-invalid text-danger",
		rules: {
			NameVariant: {
				required: true,
				minlength: 5,
			},
			IdCategory: "required",
		},
		messages: {
			NameVariant: {
				required: "Please fill Name Variant",
				minlength: "The name must consist of at least 5",
			},
			IdCategory: "Please Select Category",
		},
		//membuat validasi jika nama kategori sudah ada
		submitHandler: function(form) {
			var dataForm = $(form).serialize()
			$.ajax({
				url: "/Variant/Create",
				data: dataForm,
				method: "post",
				dataType: "json",
				success: function(respon) {
					var data = respon.dataRespon
					if (data.success) {
						$("#myModal").modal("hide")
						toastr.success(
							data.message,
							'',
							{
								timeOut: 500,
								fadeOut: 500,
								onHidden: function() {
									window.location.reload()
								}
							}
						)
					} else {
						toastr.error(data.message)
					}
				}
			})

		}
	});
</script>

xpos314/xpos314.web/Views/Variant/Delete.cshtml
@using xpos314.viewmodels
@model VMTblVariant
@{
    //Layout = null;
      ViewData["Title"] = "Delete Variant";
}

<div class="card">
    <div class="card-body">
        <form asp-action="SureDelete" method="post">
            <input type="hidden" id="Id" name="Id" value="@Model.Id"/>

            <h3>Are you sure for delete @Model.NameVariant?</h3>

            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Yes</button>
                <a asp-action="Index" class="btn btn-secondary">Back to List</a>
            </div>
        </form>
    </div>
</div>

xpos314/xpos314.web/Views/Variant/Detail.cshtml
@using xpos314.viewmodels
@model VMTblVariant
@{
	ViewData["Title"] = "Detail Variant";
}
<div class="card mt-4">
	<div class="card-body">
		<h4>@ViewData["Title"] : @Model.NameCategory</h4>
		<form asp-action="Edit" method="post" id="form_input">
			<div class="form-group row mb-2">

				<label for="NameCategory" class="col-sm-4 col-form-label">Name Variant</label>
				<div class="col-sm-8">
					<input type="text" class="form-control" name="NameVariant" id="NameVariant" value="@Model.NameVariant" readonly>
				</div>
			</div>
			<div class="form-group row mb-2">

				<label for="NameCategory" class="col-sm-4 col-form-label">Name Category</label>
				<div class="col-sm-8">
					<input type="text" class="form-control" name="NameCategory" id="NameCategory" value="@Model.NameCategory" readonly>
				</div>
			</div>
			<div class="form-group row mb-2">
				<label for="Description" class="col-sm-4 col-form-label">Description</label>
				<div class="col-sm-8">
					<input type="text" class="form-control" name="Description" id="Description" value="@Model.Description" readonly>
				</div>
			</div>
			<div class="form-group row">
				<div class="col-sm-10">
					<a class="btn btn-secondary" asp-controller="Variant" asp-action="Index">Back</a>
				</div>
			</div>
		</form>
	</div>
</div>

xpos314/xpos314.web/Views/Variant/Edit.cshtml
@using xpos314.viewmodels
@model VMTblVariant
@{
	ViewData["Title"] = "Edit Variant";
}
<div class="card mt-4">
	<div class="card-body">
		<h4>@ViewData["Title"] : @Model.NameVariant</h4>
		<form asp-action="Edit" method="post" id="form_input">
			<input type="hidden" id="Id" name="Id" value="@Model.Id" />
			<div class="form-group row mb-2">
				<label for="NameVariant" class="col-sm-4 col-form-label">Name Variant</label>
				<div class="col-sm-8">
					<input type="text" class="form-control" name="NameVariant" id="NameVariant" required value="@Model.NameVariant">
				</div>
			</div>
			<div class="form-group row mb-2">
				<label for="IdCategory" class="col-sm-4 col-form-label">Name Category</label>
				<div class="col-sm-8">
					@Html.DropDownList("IdCategory",
					new SelectList(ViewBag.ListCategory, "Id", "NameCategory"),
					"--Pilih Kategori--",
					new { @class = "form-control" }
					)
				</div>
			</div>
			<div class="form-group row mb-2">
				<label for="Description" class="col-sm-4 col-form-label">Description</label>
				<div class="col-sm-8">
					<input type="text" class="form-control" name="Description" id="Description" value="@Model.Description">
				</div>
			</div>
			<div class="form-group row">
				<div class="col-sm-10">
					<button type="submit" class="btn btn-primary">Submit</button>
					<a class="btn btn-secondary" asp-controller="Variant" asp-action="Index">Back</a>
				</div>
			</div>
		</form>
	</div>
</div>

<script>
	$("#form_input").validate({
		errorClass: "is-invalid text-danger",
		rules: {
			NameVariant: {
				required: true,
				minlength: 5,
			},
			IdCategory: "required",
		},
		messages: {
			NameVariant: {
				required: "Please fill Name Variant",
				minlength: "The name must consist of at least 5",
			},
			IdCategory: "Please Select Category",
		},
		//membuat validasi jika nama kategori sudah ada
		submitHandler: function(form) {
			var dataForm = $(form).serialize()
			$.ajax({
				url: "/Variant/Edit",
				data: dataForm,
				method: "post",
				dataType: "json",
				success: function(respon) {
					var data = respon.dataRespon
					if (data.success) {
						$("#myModal").modal("hide")
						toastr.success(
							data.message,
							'',
							{
								timeOut: 500,
								fadeOut: 500,
								onHidden: function() {
									window.location.reload()
								}
							}
						)
					} else {
						toastr.error(data.message)
					}
				}
			})

		}
	});
</script>

xpos314/xpos314.web/Views/Variant/Index.cshtml
@using System.Globalization
@using xpos314.datamodels
@using xpos314.viewmodels
@model PaginationList<VMTblVariant>

@{
	ViewData["Title"] = "Variant API";
}

<h3>Variant</h3>


<div class="card">
	<div class="card-header">
		@*        <button id="btn_create" class="btn btn-primary">Create</button>*@
		<form asp-action="Index" asp-route-pageSize="@ViewBag.CurrentPageSize">
			<div class="row mb-3">
				<div class="col-12">
					<div class="d-flex justify-content-between">
						<button type="button" class="btn btn-primary" id="btn_create" style="color:white; border-radius:5px;">
							Create
						</button>

						<div class="input-group w-50">
							<input type="text" class="form-control" id="searchString" name="searchString"
								   value="@ViewBag.currentFilter" placeholder="Search..." />
							<div class="input-group-prepend">
								<div class="input-group-text" style="cursor:pointer" id="btn_search"><i class="fas fa-search"></i></div>
							</div>
							<div class="input-group-prepend">
								@*<div class="input-group-text" style="cursor:pointer" id="btn_reset"><i class="fas fa-redo"></i></div>*@
								<a class="input-group-text" style="cursor:pointer" asp-action="index"><i class="fas fa-redo"></i></a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</form>
		<!-- /.card-header -->
		<div class="card-body table-responsive p-0">
			<table class="table table-hover mb-3">
				<thead>
					<tr>
						<th>
							<a asp-action="Index" asp-route-sortOrder="@ViewBag.NameSort">
								<i class="fas fa-sort"></i>
								Name Variant
							</a>
						</th>
						<th>
							<a asp-action="Index" asp-route-sortOrder="@ViewBag.NameSort">
								<i class="fas fa-sort"></i>
								Name Category
							</a>
						</th>
						<th>Description</th>
						<th>IsDelete</th>
						<th>Date</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
					@if (Model.Count != 0)
					{
						@foreach (var item in Model)
						{
							<tr>
								<td>@item.NameVariant</td>
								<td>@item.NameCategory</td>
								<td>@item.Description</td>
								@*<td>@item.IsDelete</td>*@
								<td>
									@if (@item.IsDelete == true)
									{
										<input type="checkbox" checked disabled/>
									}else{
										<input type="checkbox" disabled/>
									}
								</td>
								<td>@item.CreateDate.ToString("dddd, dd MMMM yyyy HH:mm:ss", new CultureInfo("id-ID"))</td>
								@*<td>@item.CreateDate.ToLongDateString()</td>*@
								@*<td>@item.CreateDate</td>*@

								<td>
									<a class="btn btn-primary btn_detail" dataid="@item.Id">Detail</a>
									<a class="btn btn-warning btn_edit" dataid="@item.Id"><i style="color:white;" data-feather="edit"></i></a>
									<a class="btn btn-danger btn_delete" dataid="@item.Id"> <i style="color:white;" data-feather="trash"></i></a>
								</td>

							</tr>
						}
					}
					else
					{
						<tr>
							<td colspan="3">
								<i>Data not found</i>
							</td>
						</tr>
					}
				</tbody>
			</table>
		</div>
		<!-- /.card-body -->

		<div class="card-footer">
			@{
				var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
				var nextDisabled = !Model.HasNextPage ? "disabled" : "";
			}
			<div class="row">
				<div class="col-2">

					<form asp-action="Index" id="form_pagesize">
						@*submitnya menggunakan jquery*@
						<select name="PageSize" id="PageSize"
								class="form-control">
							<option value="3">3</option>
							<option value="5">5</option>
							<option value="10">10</option>
						</select>
					</form>
				</div>
				<div class="col-10">
					<div class="">Entries From @Model.TotalData data</div>
					<div class="">Page @Model.PageIndex of @Model.TotalPages</div>
					<div class="col-12 d-flex justify-content-end">
						<div class="justify-content-between">

							<a asp-action="Index"
							   asp-route-sortOrder="@ViewBag.CurrentSort"
							   asp-route-pageNumber="@(Model.PageIndex + 1)"
							   asp-route-currentFilter="@ViewBag.CurrentFilter"
							   asp-route-pageSize="@ViewBag.CurrentPageSize"
							   class="btn btn-info float-right @nextDisabled">
								Next
							</a>

							<a asp-action="Index"
							   asp-route-sortOrder="@ViewBag.CurrentSort"
							   asp-route-pageNumber="@(Model.PageIndex - 1)"
							   asp-route-currentFilter="@ViewBag.CurrentFilter"
							   asp-route-pageSize="@ViewBag.CurrentPageSize"
							   class="btn btn-info float-right @prevDisabled">
								Previous
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


<script>
	$(document).ready(function() {
		$("#select_show").val(@ViewBag.currentShowData);

		$("#btn_reset").click(function() {
			$("#searchString").val("")
			$("#form_search").submit()
		})

		$("#btn_create").click(function() {
			$(".modal-body").empty()
			$(".modal-title").text("Tambah Variant")
			$(".modal-body").load("/Variant/Create")
			$("#myModal").modal("show")
		});

		$(".btn_detail").click(function() {
			var id = $(this).attr("dataid")
			$(".modal-body").empty();
			$(".modal-body").load("/Variant/Detail?id=" + id)
			$("#myModal").modal("show");
		});

		$(".btn_edit").click(function() {
			var id = $(this).attr("dataid")
			$(".modal-body").empty();
			$(".modal-body").load("/Variant/Edit?id=" + id)
			$("#myModal").modal("show");
		});

		$(".btn_delete").click(function() {
			var id = $(this).attr("dataid");
			$(".modal-body").empty();
			$(".modal-body").load("/Variant/Delete?id=" + id)
			$("#myModal").modal("show");
		});

		$("#PageSize").val(@ViewBag.CurrentPageSize)

		$("#PageSize").change(function() {
			$("#form_pagesize").submit();
		})

	});
</script>